version: '3.7'

services:
  db:
    container_name: blog_app
    image: postgres:14-alpine3.15
    ports:
      - 5433:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - blog-app-data:/var/lib/postgresql/data

volumes:
  blog-app-data:
